safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: ig
default_width: 792
default_lang: en
default_body_class: shower list

author:
    name: Varya Stepanova
    url:  http://varya.me
    company:
        name: SC5 Online (NordCloud Company)
        url:  https://sc5.io/

fork_url: https://github.com/varya/component-development-css-2017
progress: true
line_numbers: true
